sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

services:
  - elasticsearch

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.4.deb

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

before_script:
  - sleep 10

script:
  - flake8
  - py.test --cov=service_directory --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "generate with travis encrypt"
  on:
    tags: true
    all_branches: true

notifications:
  slack: praekelt:VMrETgjMuKaZW2OPrKiKINRu
  
