sudo: false
language: python
python:
  - "2.7"
cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
before_script:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.0.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch &>/dev/null &
  - sleep 10  # ElasticSearch may take a few seconds to start and may not be available when the script is executed.
script:
  - flake8
  - py.test --cov=service_directory --cov-report=term
after_success:
  - coveralls

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

jobs:
  include:
    - stage: test
    - stage: docker
      python: "2.7"
      sudo: required
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/service_directory
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "plTU4J43/SUQ5Oh+Q/fXuUPR+iruZqogRDLO2wVsuBrEr3aszW6Re+Zogef69KthWixdmTMzJPN17ukBbCmYur7wpqVh90onfEwz9fKKDfLM+I/amUdxn0qUaweV36EwRO0E+5UTLbwQvzjI+LOeIdyIdaq6G+BYqDMwdB0XsQGGDGaG0LrsmQzmLhTG4RVS/C6IkipK9wSY1Jx7Kw4UQM3bcKbLlMsu6/Wcv2i3diSCW1BIGj1mb5sluGjlG/8MwP0QYHrtxJ/X5uC8KuPO873PWcmCY/b/QEaO5fy9CW+88CDIVlLkPARtl5SZjYHM+6Bkse91Zpntjo4i+icPiK2Fhh7+pUs0z9jaBvDW0Rv64Lgap469ZBC5O5p6yvaB1S+jDVCtibIeLLo+I/3Ho0MG/BfD5mu+W8bhSX0XdqeIgYfLfvImSLVJV5zhcr7OAQHQyeYQlG42UTkVAasqONQc7WcjfEeyivL+JDjQtc+1ltKlT3GflnkwXa8oH3GKNcJxZXu3OMc8V8FoQweX27KY8tX63PNCx6N8DBOlG9dwBAM48EI/sQY4QnjajlL0/SFCEhQXN0TgYvupr9EPugdzwfkvAvVdyXAvjgywlLiIMGjnyJJYSFR+qOVb5W5VdOiTub+m4ybdiKxouoGRrHnmlgi04tTiMAi2r40JIMg="

      script:
        - docker build --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
          on:
            branch: develop

      # Built steps inherited from the default stage that we don't want
      before_install: []
      before_script: []
      install: []
      after_success: []
