sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

sudo: required

# https://docs.travis-ci.com/user/database-setup/#ElasticSearch
services:
  - elasticsearch

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

before_script:
  - sleep 10  # ElasticSearch may take a few seconds to start and may not be available when the script is executed.

script:
  - flake8
  - py.test --cov=service_directory --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "generate with travis encrypt"
  on:
    tags: true
    all_branches: true

notifications:
  slack: praekeltfoundation:mgvd7PsJynKvMoximpSmuusw
  
